"""initial_migration

Revision ID: da32a1c8cd7e
Revises: None
Create Date: 2026-06-29 09:59:25.461840

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'da32a1c8cd7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalknowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_globalknowledge_key'), 'globalknowledge', ['key'], unique=True)
    op.create_table('municipi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codi_ine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('poblacio', sa.Integer(), nullable=True),
    sa.Column('adreca_fisica', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_general', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefon_general', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipi_codi_ine'), 'municipi', ['codi_ine'], unique=True)
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipi_id', sa.Integer(), nullable=False),
    sa.Column('pla_assignat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pla_saas', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estat_kanban', sa.Enum('NOU', 'CONTACTAT', 'DEMO', 'PROPOSTA', 'TANCAT', name='estatdeal'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_creacio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proper_pas', sa.Text(), nullable=True),
    sa.Column('data_seguiment', sa.DateTime(timezone=True), nullable=True),
    sa.Column('municipality_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendari_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('municipi_id', sa.Integer(), nullable=True),
    sa.Column('data_inici', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipus', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completat', sa.Boolean(), nullable=False),
    sa.Column('es_tasca', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendari_event_deal_id'), 'calendari_event', ['deal_id'], unique=False)
    op.create_table('contacte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipi_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('carrec', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacte_email'), 'contacte', ['email'], unique=False)
    op.create_table('interaccio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('tipus', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contingut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaccio_deal_id'), 'interaccio', ['deal_id'], unique=False)
    op.create_index(op.f('ix_interaccio_tipus'), 'interaccio', ['tipus'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaccio_tipus'), table_name='interaccio')
    op.drop_index(op.f('ix_interaccio_deal_id'), table_name='interaccio')
    op.drop_table('interaccio')
    op.drop_index(op.f('ix_contacte_email'), table_name='contacte')
    op.drop_table('contacte')
    op.drop_index(op.f('ix_calendari_event_deal_id'), table_name='calendari_event')
    op.drop_table('calendari_event')
    op.drop_table('deal')
    op.drop_index(op.f('ix_municipi_codi_ine'), table_name='municipi')
    op.drop_table('municipi')
    op.drop_index(op.f('ix_globalknowledge_key'), table_name='globalknowledge')
    op.drop_table('globalknowledge')
    # ### end Alembic commands ###
