"""add is_completed to interaccio

Revision ID: e79a3718eb10
Revises: d3ffd629e673
Create Date: 2026-04-27 03:35:13.551217

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e79a3718eb10'
down_revision = 'd3ffd629e673'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaccio', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # Posem el valor per defecte a False per als registres existents
    op.execute("UPDATE interaccio SET is_completed = FALSE WHERE is_completed IS NULL")
    # Fem que sigui no nul·lable un cop omplert
    op.alter_column('interaccio', 'is_completed', nullable=False, server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interaccio', 'is_completed')
    # ### end Alembic commands ###
