"""create_calendari_event_table

Revision ID: ff0dbc4b03eb
Revises: ce6eb274cb5f
Create Date: 2026-04-28 21:31:43.635993

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ff0dbc4b03eb'
down_revision = 'ce6eb274cb5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
